# Nacos: dev命名空间 > common.yaml
# 公共配置，所有服务共享

spring:
  jackson:
    default-property-inclusion: non_null
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss
  
  # 数据库连接池通用配置
  datasource:
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 3
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  
  # 事务配置
  transaction:
    default-timeout: 30

  
  # 线程池配置
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100

# MyBatis通用配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true
    lazy-loading-enabled: true
    multiple-result-sets-enabled: true
    use-column-label: true
    use-generated-keys: true
    default-statement-timeout: 30

# JWT通用配置
jwt:
  secret: ${JWT_SECRET:ajogjsofjscmolusojclskmsdlgoujoiafjmsldkcmdsgjioawejhnklasdclksdghasjklfnslkdfnmlkdscjsdkohganksldmnssldkcmnsdghnasdkjfmnsdklcmsdklhgjkladmclksmnjksdngmcgnfaksljfmndsklchndsjknfga}
  expireMinutes: ${JWT_EXPIRATION:24800}

# 跨域通用配置
cors:
  allow-origins: "${CORS_ALLOW_ORIGINS:*}"
  allow-methods: "${CORS_ALLOW_METHODS:GET,POST,PUT,DELETE,OPTIONS}"
  allow-headers: "${CORS_ALLOW_HEADERS:Content-Type,Authorization}"
  allow-credentials: ${CORS_ALLOW_CREDENTIALS:false}

# 日志通用配置
logging:
  level:
    com.djy.quiz: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.alibaba.nacos: WARN

# 应用通用配置
app:
  name: ${spring.application.name}
  version: 1.0.0
  description: Quiz Application