# Data ID: datasource-answer-service.yaml
# Group: DEFAULT_GROUP

spring:
  datasource:
    url: jdbc:mysql://answer-db:3306/quiz?useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 15
      minimum-idle: 5
  # Flyway/Liquibase数据库迁移配置
  flyway:
    enabled: true
    locations: classpath:db/migration/question
    baseline-on-migrate: true
    baseline-version: 0
    validate-on-migrate: true

# 数据库连接监控
datasource:
  monitoring:
    slow-query-threshold: 1000  # 1秒
    log-slow-queries: true