# Nacos: dev命名空间 > gateway-service.yaml

server:
  port: ${SERVER_PORT:8090}

spring:
  application:
    name: gateway-service
  
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      
      # 路由配置
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/user/**
          filters:
            - name: JwtGatewayFilter
              args:
                whiteList: /api/user/register,/api/user/login,/api/user/health
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
        
        - id: question-service
          uri: lb://question-service
          predicates:
            - Path=/api/quiz/**
          filters:
            - name: JwtGatewayFilter
            - StripPrefix=1
        
        - id: answer-service
          uri: lb://answer-service
          predicates:
            - Path=/api/answer/**
          filters:
            - name: JwtGatewayFilter
            - StripPrefix=1
        
        # 健康检查路由
        - id: health-check
          uri: lb://user-service
          predicates:
            - Path=/health/**
          filters:
            - StripPrefix=0
        
        # 监控端点路由
        - id: actuator
          uri: http://localhost:${server.port}
          predicates:
            - Path=/actuator/**
          filters:
            - name: AuthenticationFilter
              args:
                rolesAllowed: ADMIN
    
    # 限流配置
    redis:
      rate-limiter:
        enabled: true
    
    # Sentinel配置
    sentinel:
      enabled: true
      transport:
        dashboard: localhost:8080
      scg:
        fallback:
          mode: response
          response-status: 429
          response-body: "Too Many Requests"

# JWT配置
jwt:
  secret: ${JWT_SECRET:ajogjsofjscmolusojclskmsdlgoujoiafjmsldkcmdsgjioawejhnklasdclksdghasjklfnslkdfnmlkdscjsdkohganksldmnssldkcmnsdghnasdkjfmnsdklcmsdklhgjkladmclksmnjksdngmcgnfaksljfmndsklchndsjknfga}
  expiration: ${JWT_EXPIRATION:86400000}
  header: Authorization
  prefix: Bearer

# 跨域配置
cors:
  allow-origins: "${CORS_ALLOW_ORIGINS:*}"
  allow-methods: "${CORS_ALLOW_METHODS:GET,POST,PUT,DELETE,OPTIONS}"
  allow-headers: "${CORS_ALLOW_HEADERS:Content-Type,Authorization,X-Token-Source,X-User-Id,X-User-Name,X-User-Role}"
  allow-credentials: false

# 网关安全配置
security:
  whitelist:
    - /api/user/login
    - /api/user/register
    - /health/**
    - /actuator/health
    - /actuator/info
  
  # IP白名单
  ip-whitelist:
    - 127.0.0.1
    - 192.168.0.0/16
    - 10.0.0.0/8

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway,metrics,prometheus
    health:
      show-details: when-authorized
  metrics:
    tags:
      application: ${spring.application.name}
    export:
      prometheus:
        enabled: true

# 网关性能配置
gateway:
  performance:
    max-concurrent-requests: 1000
    request-timeout: 30s
    connect-timeout: 5s