# Nacos: dev命名空间 > user-service.yaml

server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: user-service
  
# MyBatis配置
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.djy.quiz.user.pojo.model

# 服务特定配置
service:
  user:
    default-role: USER
    password:
      salt-rounds: 10
    token:
      expiration: 24h
    
  # 缓存配置
  cache:
    user-by-id:
      ttl: 300s  # 5分钟
    user-by-username:
      ttl: 300s

# 接口配置
api:
  auth:
    login:
      max-attempts: 5
      lock-duration: 30m
    register:
      enabled: true
      require-email-verification: false
  
  # 用户管理
  user:
    list:
      default-page-size: 20
      max-page-size: 100
    profile:
      avatar:
        max-size: 2MB
        allowed-types: jpg,jpeg,png,gif

# 健康检查配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
    health:
      show-details: when-authorized
  metrics:
    export:
      prometheus:
        enabled: true